# Clone the git repo.
#id field to set a unique identifier for a build step.
# <github_repository> is the name of the gethub repository to be clone
#args take a list of arguments
steps:
  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone'
    args: ['clone', 'https://github.com/rui-s-costa/spring-hello.git']

  - name: maven:3-jdk-8
    entrypoint: mvn
    args: [ 'test' ]

  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']

  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', 'gcr.io/qwiklabs-gcp-02-bea1b946eb90/spring-hello:latest', '--build-arg=JAR_FILE=target/*.jar', '.' ]

#  # pushes the image to Container Registry
#  - name: 'gcr.io/cloud-builders/docker'
#    id: Push
#    args:
#      - 'push'
#      - 'gcr.io/$PROJECT_ID/spring-hello:latest'

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deployment.yaml
      - --image=gcr.io/qwiklabs-gcp-02-bea1b946eb90/spring-hello:latest
      - --location=us-central1
      - --cluster=qwiklabs-gcp-02-bea1b946eb90-gke